version: '2'
volumes:
  ${volumes_section}
services:
  admin:
    tty: true
    image: frolvlad/alpine-bash
    external_links:
      ${external_links}
    volumes:
      ${volumes}
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$$$${stack_name}/$$$${service_name}
      io.rancher.scheduler.affinity:host_label: ${label_global_scheduling}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always